version: "3.8"

services:
  store-api-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "5123:5123"
        - "5443:5443"
    volumes:
      - ..:/api/
    working_dir: /api/
    stdin_open: true
    tty: true
